app = 'peermesh-relay'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  API_BASE = 'https://peermesh-0unl.onrender.com'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 400

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[[restart]]
  policy = 'always'
  max_retries = 10
